name: xplore_cusco
description: "Turismo en Cusco."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.4.0
  provider: ^6.1.1
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  google_maps_flutter: ^2.5.0  # <-- Se queda esta
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  go_router: ^14.0.1
  get_it: ^8.0.0
  shared_preferences: ^2.3.3
  lottie: ^3.1.0
  flutter_staggered_animations: ^1.0.0
  url_launcher: ^6.3.1

  firebase_core: ^2.15.0
  firebase_storage: ^11.2.0
  cached_network_image: ^3.3.0


  # GEOLOCALIZACIÓN Y MAPAS
  # google_maps_flutter: ^2.5.0  <-- SE ELIMINÓ ESTA (DUPLICADA)
  geolocator: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.webp
    - assets/xplora_cusco_logo.png
    - assets/log.png
    - assets/imagenes/mapa_textura.png
   # - assets/animaciones/viaje.json

# Configuración del splash nativo (ajústala si quieres)
flutter_native_splash:
  color: "#121212"
  image: assets/xplora_cusco_logo.png
  android: true
  ios: true
  android_12:
    image: assets/xplora_cusco_logo.png
    icon_background_color: "#121212"
  ios_content_mode: center